export const SET_USER = 'SET_USER';
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS';
export const INCREMENT_PRODUCTS_PAGE = 'INCREMENT_PRODUCTS_PAGE';
export const DECREMENT_PRODUCTS_PAGE = 'DECREMENT_PRODUCTS_PAGE';